export const Course = [
  {
    id: 1,
    title: "Course 1",
    description: "Course 1 Description",
    category: "Category 1",
  },
  {
    id: 2,
    title: "Course 2",
    description: "Course 2 Description",
    category: "Category 2",
  },
  {
    id: 3,
    title: "Course 3",
    description: "Course 3 Description",
    category: "Category 3",
  },
  {
    id: 4,
    title: "Course 4",
    description: "Course 4 Description",
    category: "Category 4",
  },
  {
    id: 5,
    title: "Course 5",
    description: "Course 5 Description",
    category: "Category 5",
  },
  {
    id: 6,
    title: "Course 6",
    description: "Course 6 Description",
    category: "Category 6",
  },
  {
    id: 7,
    title: "Course 7",
    description: "Course 7 Description",
    category: "Category 7",
  },
  {
    id: 8,
    title: "Course 8",
    description: "Course 8 Description",
    category: "Category 8",
  },
  {
    id: 9,
    title: "Course 9",
    description: "Course 9 Description",
    category: "Category 9",
  },
  {
    id: 10,
    title: "Course 10",
    description: "Course 10 Description",
    category: "Category 10",
  },
  {
    id: 11,
    title: "Course 11",
    description: "Course 11 Description",
    category: "Category 11",
  },
  {
    id: 12,
    title: "Course 12",
    description: "Course 12 Description",
    category: "Category 12",
  },
  {
    id: 13,
    title: "Course 13",
    description: "Course 13 Description",
    category: "Category 13",
  },
  {
    id: 14,
    title: "Course 14",
    description: "Course 14 Description",
    category: "Category 14",
  },
  {
    id: 15,
    title: "Course 15",
    description: "Course 15 Description",
    category: "Category 15",
  },
]
